Correct formatting to follow editorconfig
Mixing spaces and tabs for indentation is never good...

diff --git a/tuhustp b/tuhustp
--- a/tuhustp
+++ b/tuhustp
@@ -89,7 +89,6 @@ write_to_file () {
         [ -n "$DBGOUT" ] && printf '%s\n' "$value"
         [ -z "$DRYRUN" ] && printf '%s\n' "$value" > "$file"
     fi
-
 }
 
 show_usage () {
@@ -118,7 +117,7 @@ while [ "$#" -gt 0 ]; do
         d)  DBGOUT=1 ;;
         n)  DRYRUN=1 ;;
         h) show_help ;;
-        *) 
+        *)
             echo "${myname}: unknown flag '${o}'"
             show_usage
             exit 1
@@ -171,36 +170,36 @@ NumPaths=$(wc -l "$PathsFile" | cut -d' ' -f1 )
 # start counter
 NumLine=1
 while [ $NumLine -le "$NumPaths" ]; do
-	# cd to dir of nth game found
-	cd "$(sed 's/th[0-9]*[0-9].exe$//;'$NumLine'q;d' "$PathsFile")" || die "could not cd to dir"
+    # cd to dir of nth game found
+    cd "$(sed 's/th[0-9]*[0-9].exe$//;'$NumLine'q;d' "$PathsFile")" || die "could not cd to dir"
 
-	# read the numbers from the exe filename
-	TouhouNum=$(echo th*[!e].exe|cut -c 3-|head --bytes -5)
+    # read the numbers from the exe filename
+    TouhouNum=$(echo th*[!e].exe|cut -c 3-|head --bytes -5)
 
-	# check if an additional patched exe exists
-	if [ -f th"$TouhouNum"e.exe  ]; then
-		# set the name of the additional patched exe for the run script
-		TouhouNumE="${TouhouNum}e"
-	else
-		# set the name of the only exe for the run script
-		TouhouNumE=$TouhouNum
-	fi
+    # check if an additional patched exe exists
+    if [ -f th"$TouhouNum"e.exe  ]; then
+        # set the name of the additional patched exe for the run script
+        TouhouNumE="${TouhouNum}e"
+    else
+        # set the name of the only exe for the run script
+        TouhouNumE=$TouhouNum
+    fi
 
-	# create missing icons if the tools are avaible
-	if [ ! -f Icon_th"$TouhouNum".png  ]; then
+    # create missing icons if the tools are avaible
+    if [ ! -f Icon_th"$TouhouNum".png  ]; then
         echo "there is no icon file for $TouhouNum"
-		if [ $CanCreateIcon = 1 ]; then
-			echo "creating icon for th$TouhouNum"
-			wrestool -x -t 14 th"$TouhouNum".exe > out.ico
-			icotool -x -o . out.ico
-			mv out*.png Icon_th"$TouhouNum".png
-			rm out.ico
+        if [ $CanCreateIcon = 1 ]; then
+            echo "creating icon for th$TouhouNum"
+            wrestool -x -t 14 th"$TouhouNum".exe > out.ico
+            icotool -x -o . out.ico
+            mv out*.png Icon_th"$TouhouNum".png
+            rm out.ico
         else
             echo "missing icons can't be created please install icoutils and re-run"
-		fi
-	fi
+        fi
+    fi
 
-	CurrentDirPath="$(pwd)"
+    CurrentDirPath="$(pwd)"
     printf '\n'
     RunscriptFile="${HOME}/.local/bin/touhou-${TouhouNum}"
     printf '%s %5s: %s\n' "creating runscript for" "th$TouhouNum" "$RunscriptFile"
@@ -211,11 +210,11 @@ while [ $NumLine -le "$NumPaths" ]; do
 
     printf '\n'
     DesktopFile="${HOME}/.local/share/applications/th${TouhouNum}.desktop"
-	printf '%s %5s: %s\n' "creating launcher  for" "th$TouhouNum" "$DesktopFile"
+    printf '%s %5s: %s\n' "creating launcher  for" "th$TouhouNum" "$DesktopFile"
     create_desktopfile "$CurrentDirPath" "$TouhouNum" | write_to_file "$DesktopFile"
 
-	NumLine=$((NumLine + 1))
-	cd "$StartDir" || die "could not cd to '$StartDir'"
+    NumLine=$((NumLine + 1))
+    cd "$StartDir" || die "could not cd to '$StartDir'"
 done
 
 cd "$StartDir" || die "could not cd to '$StartDir'"
